---
title: "R Notebook"
output: html_notebook
---
```{r Read data in, base plot}
#Read in data
krill <- read.csv("C:/Users/Danielle.Perez/Documents/Krill 2019/EndofStudyKrill_organizedbyFASTINGhours.csv")

#Remove unecessary columns
krill <- krill[-c(2, 5:7, 10:11, 13:26)]

#Rename columns
names(krill)[4] <- "telsonLength"
names(krill)[5] <- "wetWeight"

#Change MOATS to factor
krill$MOATS<-as.factor(krill$MOATS)
krill$telsonLength<-as.numeric(krill$telsonLength)

#Basic plot comparing telson length and wet weight
plot(krill$telsonLength, krill$wetWeight*1000)
```

```{r ggplot, yo}
library(ggplot2)

#Pretty scatter plot of all length vs. weight
ggplot(krill, aes(telsonLength, wetWeight*1000)) + 
  geom_point(aes(colour = Treatment))  +
  geom_smooth(method = "lm") +
  ggtitle("Krill telson length vs. wet weight") + xlab("Telson length (mm)") + ylab("Wet weight (mg)")

#Facet wrap plot (by treatment)
ggplot(krill, aes(telsonLength, wetWeight*1000, colour = MOATS)) + 
   geom_point() + ggtitle("Krill telson length vs. wet weight") + xlab("Telson length (mm)") + ylab("Wet weight (mg)") +
   facet_wrap(~ Treatment)

#Facet wrap plot (by MOATS)
ggplot(krill, aes(telsonLength, wetWeight*1000, colour = Treatment)) + 
   geom_point() + ggtitle("Krill telson length vs. wet weight") + xlab("Telson length (mm)") + ylab("Wet weight (mg)") +
   facet_wrap(~ MOATS)

```

```{r just some boxplots}

ggplot(krill, aes(telsonLength, wetWeight*1000, color = Treatment)) +
  geom_boxplot() +
  ggtitle("Krill telson length vs. wet weight") + xlab("Telson length (mm)") + ylab("Wet weight (mg)")

ggplot(krill, aes(telsonLength, wetWeight*1000, color = Treatment)) + 
  geom_boxplot(notch = TRUE) + geom_jitter(shape=16, position=position_jitter(0.2)) +
  ggtitle("Krill telson length vs. wet weight") + xlab("Telson length (mm)") + ylab("Wet weight (mg)")
 
```

```{r Stats, yo}
library(tidyr)

#Remove NAs
krill <- na.omit(krill)

#Calculate mean and standard deviation for each treatment
TL_Avg <- tapply(krill$telsonLength, (krill$Treatment), mean)
TL_Med <- tapply(krill$telsonLength, (krill$Treatment), median)
TL_Std <- tapply(krill$telsonLength, (krill$Treatment), sd)
WW_Avg <- tapply(krill$wetWeight, (krill$Treatment), mean)
WW_Med <- tapply(krill$wetWeight, (krill$Treatment), median)
WW_Std <- tapply(krill$wetWeight, (krill$Treatment), sd)

#Put it all together
Krill_Stats <- cbind(TL_Avg, TL_Med, TL_Std, WW_Avg, WW_Med, WW_Std)
colnames(Krill_Stats) [1:6] <-c("Average telson Length", "Median Telson Length", "Telson Length SD", "Average Wet Weight", "Median Wet Weight", "Wet Weight SD")

#And what do you got
View(Krill_Stats)
write.csv(Krill_Stats, "C:/Users/Danielle.Perez/Documents/Krill 2019/krillSize/krillStats.csv")
```

```{r Cannibalizing Emmas code for telson length}
### LENGTH STATISTICS

#Function to calculate standard errors and CI for error bars
## Gives count, mean, standard deviation, standard error of the mean, and confidence interval (default 95%).
##   data: a data frame.
##   measurevar: the name of a column that contains the variable to be summarized
##   groupvars: a vector containing names of columns that contain grouping variables
##   na.rm: a boolean that indicates whether to ignore NA's
##   conf.interval: the percent range of the confidence interval (default is 95%)

summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
  library(plyr)
  
  # New version of length which can handle NA's: if na.rm==T, don't count them
  length2 <- function (x, na.rm=FALSE) {
    if (na.rm) sum(!is.na(x))
    else       length(x)
  }
  
  # This does the summary. For each group's data frame, return a vector with
  # N, mean, and sd
  datac <- ddply(data, groupvars, .drop=.drop,
                 .fun = function(xx, col) {
                   c(N    = length2(xx[[col]], na.rm=na.rm),
                     mean = mean   (xx[[col]], na.rm=na.rm),
                     sd   = sd     (xx[[col]], na.rm=na.rm)
                   )
                 },
                 measurevar
  )
  
    # Rename the "mean" column    
  datac <- rename(datac, c("mean" = measurevar))
  
  datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean
  
  # Confidence interval multiplier for standard error
  # Calculate t-statistic for confidence interval: 
  # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
  ciMult <- qt(conf.interval/2 + .5, datac$N-1)
  datac$ci <- datac$se * ciMult
  
  return(datac)
}

summaryForErrorBars <- summarySE(data = krill, measurevar = "telsonLength", 
                                 groupvars = c("MOATS", "Treatment"), na.rm = TRUE)

summaryForErrorBars$upperBar <- summaryForErrorBars$telsonLength + summaryForErrorBars$ci
summaryForErrorBars$lowerBar <- summaryForErrorBars$telsonLength - summaryForErrorBars$ci

ggplot(summaryForErrorBars, aes(x = Treatment, y = telsonLength, colour = MOATS)) +
  geom_errorbar(aes(ymin = lowerBar, ymax = upperBar))+
  geom_point(size = 3) +
  geom_jitter(data=krill, aes(x = Treatment, y = telsonLength, colour = MOATS), alpha = 0.4,
              position = position_jitter(0.4)) +
  ggtitle("Treatment Comparison of Telson Length") + 
  theme_bw(base_size = 15) 

#separate confidence intervals by stage (not sure if we really need this or not)
ggplot(summaryForErrorBars, aes(x = MOATS,y = telsonLength)) +
  geom_errorbar(aes(ymin = lowerBar, ymax = upperBar))+
  geom_point(size = 3) +
  geom_jitter(data = krill, aes(x = MOATS,y = telsonLength), alpha = 0.4,
              position = position_jitter(0.4)) +
  ggtitle("Treatment Comparison by MOATS") + 
  facet_wrap(~Treatment) + 
  theme_bw(base_size = 15)
```

```{r Do the same thing for weight?}
### Weight STATISTICS

#Function to calculate standard errors and CI for error bars
## Gives count, mean, standard deviation, standard error of the mean, and confidence interval (default 95%).
##   data: a data frame.
##   measurevar: the name of a column that contains the variable to be summarized
##   groupvars: a vector containing names of columns that contain grouping variables
##   na.rm: a boolean that indicates whether to ignore NA's
##   conf.interval: the percent range of the confidence interval (default is 95%)

summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
  library(plyr)
  
  # New version of length which can handle NA's: if na.rm==T, don't count them
  length2 <- function (x, na.rm=FALSE) {
    if (na.rm) sum(!is.na(x))
    else       length(x)
  }
  
  # This does the summary. For each group's data frame, return a vector with
  # N, mean, and sd
  datac <- ddply(data, groupvars, .drop=.drop,
                 .fun = function(xx, col) {
                   c(N    = length2(xx[[col]], na.rm=na.rm),
                     mean = mean   (xx[[col]], na.rm=na.rm),
                     sd   = sd     (xx[[col]], na.rm=na.rm)
                   )
                 },
                 measurevar
  )
  
    # Rename the "mean" column    
  datac <- rename(datac, c("mean" = measurevar))
  
  datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean
  
  # Confidence interval multiplier for standard error
  # Calculate t-statistic for confidence interval: 
  # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
  ciMult <- qt(conf.interval/2 + .5, datac$N-1)
  datac$ci <- datac$se * ciMult
  
  return(datac)
}

summaryForErrorBars <- summarySE(data = krill, measurevar = "wetWeight", 
                                 groupvars = c("MOATS", "Treatment"), na.rm = TRUE)

summaryForErrorBars$upperBar <- summaryForErrorBars$wetWeight + summaryForErrorBars$ci
summaryForErrorBars$lowerBar <- summaryForErrorBars$wetWeight - summaryForErrorBars$ci

ggplot(summaryForErrorBars, aes(x = Treatment, y = wetWeight, colour = MOATS)) +
  geom_errorbar(aes(ymin = lowerBar, ymax = upperBar))+
  geom_point(size = 3) +
  geom_jitter(data=krill, aes(x = Treatment, y = wetWeight, colour = MOATS), alpha = 0.4,
              position = position_jitter(0.4)) +
  ggtitle("Treatment Comparison of Wet Weight") + 
  theme_bw(base_size = 15) 

#separate confidence intervals by stage (not sure if we really need this or not)
ggplot(summaryForErrorBars, aes(x = MOATS,y = wetWeight)) +
  geom_errorbar(aes(ymin = lowerBar, ymax = upperBar))+
  geom_point(size = 3) +
  geom_jitter(data = krill, aes(x = MOATS,y = wetWeight), alpha = 0.4,
              position = position_jitter(0.4)) +
  ggtitle("Treatment Comparison by MOATS") + 
  facet_wrap(~Treatment) + 
  theme_bw(base_size = 15)
```

```{r Repeated measures analysis}
#Using a mixed model to find significant differences
#Honestly don't know if I'm doing this part right, probably not

#library(nlme)
#library(lme4)
#library(lmerTest)

#overall statistical significance for telson length
fitTreatTelLength <- lmer(telsonLength ~ Treatment + (1|MOATS), data = krill)
summary(fitTreatTelLength)

#overall statistical significance for wet weight
fitTreatWetWeight <- lmer(wetWeight ~ Treatment + (1|MOATS), data = krill)
summary(fitTreatWetWeight)

#p value = 0.00525, overall treatment is significant
#Don't think anything is significant, but not sure where ambient is?
##There is more to Emma's code, but not sure how relevant it is since she was looking at stage as well as cL at different treatments##
```

